Histogram
datakaveri/differential-privacy pull request #10
Opened 2023-04-06 11:53 UTC by SarthakSharm

Extended the pipeline to support categorical histogram data.

2023-04-18 18:14 UTC, novoneel-iudx requested changes
add second query as well

2023-04-27 08:47 UTC, SarthakSharm commented on scripts/modules.py
> +        new_cols = new_cols.rename(columns={0: col + '_num', 1: col + '_str'})
We aren't using this function anyway, should I remove the whole function?

2023-05-01 05:50 UTC, novoneel-iudx approved these changes

2023-05-01 09:35 UTC, novoneel-iudx approved these changes

2023-05-01 09:35 UTC, novoneel-iudx approved these changes

2023-05-01 09:36 UTC, novoneel-iudx approved these changes

2023-05-01 09:36 UTC, closed without merging